### PR TITLE
Feature/perf improvements

### PR DESCRIPTION
**Pull request by st3v3nhunt**
This is good for review and uses the branch from https://github.com/nhsuk/moment-opening-times/pull/62 which means when that branch is deleted this PR will fail to build. At the point of PR merge, the latest version of `moment-opening-times` should be published to npm. This PR will need updating to use it.

### CODE REVIEW

**Comment by neilbmclaughlin** [comment]
LGTM

If you rebase and point it at the published npm package then I'll merge.

**Comment by st3v3nhunt** [comment]
@neilbmclaughlin Rebased, and updated to use the latest version of the newly published `moment-opening-times` lib.

**Comment by adamgraves-choices** [comment]
@st3v3nhunt should the `processed*txt`  files be in the root of the repo?

**Comment by st3v3nhunt** [comment]
@adamgraves-choices No, good spot. I've removed them.

**Pull request merged**
