### PR TITLE
Use common CI scripts

### PR DESCRIPTION
**Pull request by neilbmclaughlin**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://nearby-services-api-pr-52.dev.c2s.nhschoices.net](http://nearby-services-api-pr-52.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://nearby-services-api-pr-52.dev.c2s.nhschoices.net](http://nearby-services-api-pr-52.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://nearby-services-api-pr-52.dev.c2s.nhschoices.net](http://nearby-services-api-pr-52.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://nearby-services-api-pr-52.dev.c2s.nhschoices.net](http://nearby-services-api-pr-52.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://nearby-services-api-pr-52.dev.c2s.nhschoices.net](http://nearby-services-api-pr-52.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://nearby-services-api-pr-52.dev.c2s.nhschoices.net](http://nearby-services-api-pr-52.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://nearby-services-api-pr-52.dev.c2s.nhschoices.net](http://nearby-services-api-pr-52.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://nearby-services-api-pr-52.dev.c2s.nhschoices.net](http://nearby-services-api-pr-52.dev.c2s.nhschoices.net)

**Comment by neilbmclaughlin** [comment]
At long last this is working. Many build deployment and failures which may or may not have been due to Travis.

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://nearby-services-api-pr-52.dev.c2s.nhschoices.net](http://nearby-services-api-pr-52.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://nearby-services-api-pr-52.dev.c2s.nhschoices.net](http://nearby-services-api-pr-52.dev.c2s.nhschoices.net)

**Pull request merged**
